### ISSUE TITLE
"Player was killed by magic" only possible death message when more than one person is online.

### ISSUE THREAD

**Issue by ghost** [CreativeMD/PlayerRevive#58] opened 2021-01-17 07:47 UTC
I have a server I rent out of a different location. When I log in with only one account, I get the correct death message every time. But as soon as I log into the server with a second account to test, the dead message ONLY changes to "killed by magic" regardless of the damage source.

Other issues include: No "Player is bleeding" message when someone goes down anymore, either.

**Comment by CreativeMD** [comment] 2021-04-08 16:01
I could not reproduce this issue with just PlayerRevive installed, so it's probably an issue caused by another mod. I will rewrite PlayerRevive soon anyway, so I will close this issue for now.

**Closed as completed by CreativeMD** 2021-04-08 16:01 UTC
