### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by 1ost** [CreativeMD/PlayerRevive#38] opened 2019-09-17 18:55 UTC
after I die or revive my fps heavily drop for around 10 seconds

**Comment by CreativeMD** [comment] 2019-09-20 13:57
Maybe it's caused by the sound effect? Is there anything in the logs?

**Comment by CreativeMD** [comment] 2019-10-20 16:04
I will close this issue for now. If this issue persists just reopen it and it would be very helpful if you could provide the logs as well.

**Closed as completed by CreativeMD** 2019-10-20 16:04 UTC
