### ISSUE TITLE
Bug, you can stand up again by leaving the game and entering again

### ISSUE THREAD

**Issue by ArchiDreamZ** [CreativeMD/PlayerRevive#116] opened 2023-01-20 11:36 UTC
The version is Forge-1.19.2-v2.0.14，Players only need to disconnect and re-enter, and they can stand up again from the injured state

**Comment by CreativeMD** [comment] 2023-01-20 12:07
What other mods do you have installed? Or you using mohist or magma?

**Comment by ArchiDreamZ** [comment] 2023-01-22 13:28
I tested it out, it's a problem caused by the Spice of Life: Sweet Potato Edition mod, which makes disconnecting in the downed state not produce a death event

**Comment by ArchiDreamZ** [comment] 2023-01-22 13:35
Sorry I didn't see other issues

**Comment by CreativeMD** [comment] 2023-01-23 08:17
Oh ok ... so it is a duplicate of this https://github.com/CreativeMD/PlayerRevive/issues/114
Will close this one here ... I hope the issue can be solved eventually.

**Closed as completed by CreativeMD** 2023-01-23 08:17 UTC

**Comment by KateReller** [comment] 2024-02-26 06:33
I am getting this issue on 1.20.1 and not with this mod. 

Here's the debug logs of the server that has this mod.
[debug.log](https://mclo.gs/a5fBbnk)

**Comment by CreativeMD** [comment] 2024-02-27 11:03
@KateReller there are a few other mods which also cause a similar issue like FirstAid. You have quite a few mods installed no idea what the problem is in your case. Would be very cool if you can test it (by removing some mods and see if it is still there till you find the problematic one). If you can figure that out please open a new issue. Maybe the compatibility can be solved.
