### ISSUE TITLE
Bug when a player dies

### ISSUE THREAD

**Issue by Fred09x** [CreativeMD/PlayerRevive#74] opened 2021-10-28 13:22 UTC
Hello, sorry I have a problem with the mod on my server, when a player is dead he can continue to move, obviously it is a bug because the player cannot eat or run when this problem happens, Another thing I have to mention is that I also have the "Corail Tombstone" mod installed and I don't know if the error is from this mod, although I don't think because the mod works fine for me, because checking the server log I could see that the Corail Tombstone mod marks the following error: 

[16:31:30] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: McLennonn is bleeding...
[16:31:30] [Server thread/INFO] [tombstone]: The death event of the player McLennonn was cancelled by another mod
[16:31:53] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: McLennonn lost connection: Disconnected

**Comment by CreativeMD** [comment] 2021-10-29 10:53
If you are using 1.16/ 1.17 the player is supposed to move. It's not a bug but a feature.

**Comment by Fred09x** [comment] 2021-10-29 17:56
> If you are using 1.16/ 1.17 the player is supposed to move. It's not a bug but a feature.

I am using version 1.12.2 of the game, and what I mean is that it is assumed that when a player dies, his body should be on the ground to be revived, but it is not like that, the player continues to move and does not receive damage, the life and hunger bars do not go down or go up either, so I think it is a bug, so I want you to confirm to me if as you say this is also a feature for this version of minecraft, if so, I would be very grateful if you would explain to me how disable this to return to the way it was before.

**Comment by CreativeMD** [comment] 2021-10-30 07:34
That is definitely a bug. Is PotionsCore installed (it can cause such behavior)?

**Comment by Fred09x** [comment] 2021-11-03 17:52
> That is definitely a bug. Is PotionsCore installed (it can cause such behavior)?

PotionsCore is not installed, so I don't know the cause of the error.

**Comment by CreativeMD** [comment] 2021-11-05 09:04
Can you show me your mod list, you can also send me a log file for that.

**Comment by Fred09x** [comment] 2021-11-05 13:52
![Captura de pantalla (237)](https://user-images.githubusercontent.com/92692738/140521010-b6e3a3b7-5969-40bd-be79-7fa7f5b392cc.png)

**Comment by Fred09x** [comment] 2021-11-05 13:52
> Can you show me your mod list, you can also send me a log file for that.
![Captura de pantalla (237)](https://user-images.githubusercontent.com/92692738/140521185-9fa6d6c2-4a2c-4ccd-99d7-5ba5612efbe8.png)

**Comment by CreativeMD** [comment] 2021-11-05 15:00
I don't see any mod that I know causes trouble. I guess there are only two options. Either remove PlayerRevive or search for the conflicting mod by trail and error. Just remove half of the mods and see if the issue still occurs, if yes you need to remove more mods, if no you removed the conflicting mod and have to check the other half of the mods.

**Comment by CreativeMD** [comment] 2021-12-07 11:16
I will close this issue for now. If there any news let me know here.

**Closed as completed by CreativeMD** 2021-12-07 11:16 UTC

**Comment by walpru** [comment] 2023-04-11 04:32
Hello there, i got the same problem and have no way to figure what is causing the bug.
Has anybody solved this? How can I solve it?

**Comment by CreativeMD** [comment] 2023-04-12 09:39
This was quite some time ago. Most likely this issue is caused by mods which add gravestones. Best way to figure it out is to remove half of the mods and see if the issue still persists. Do this until you found out the mod which causes the issue. Then you can decide whether you want to remove it or get rid of PlayerRevive.
